### ISSUE TITLE
wrong index

### ISSUE THREAD

**Issue by berndhahnebach** [boltsparts/boltsparts.github.io#1]
Hi Johannes,

I am not able to display the page. Might be the index.html is wrong ?  The /bolts/ needs to be removed in the main index.html to get the page up localy on my machine if i download the page repo.

cheers bernd

I like this github pages. I ever wanted to give this a try  :-)

**Comment by jreinhardt** [comment]
Fixed

**Comment by berndhahnebach** [comment]
its up :-)

<img width="1104" alt="Unbenannt" src="https://user-images.githubusercontent.com/6129869/58534569-efae8380-81eb-11e9-99bf-c10365355301.PNG">
